/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SocialSaverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/downloader.ts
var import_obsidian = require("obsidian");

// src/security.ts
var THREADS_HOSTS = /* @__PURE__ */ new Set([
  "threads.net",
  "www.threads.net",
  "threads.com",
  "www.threads.com"
]);
var INSTAGRAM_HOSTS = /* @__PURE__ */ new Set([
  "instagram.com",
  "www.instagram.com",
  "instagr.am",
  "www.instagr.am"
]);
var MEDIA_HOST_SUFFIXES = ["cdninstagram.com", "fbcdn.net"];
var ID_PATTERN = /^[A-Za-z0-9_.-]+$/;
var USERNAME_PATTERN = /^[A-Za-z0-9._]+$/;
function safeUrl(value) {
  try {
    if (/[\u0000-\u001F\u007F]/.test(value)) return null;
    const url = new URL(value.trim());
    if (url.protocol !== "https:" || url.username || url.password || url.port) {
      return null;
    }
    return url;
  } catch {
    return null;
  }
}
function parseSupportedSocialUrl(value) {
  const url = safeUrl(value);
  if (!url) return null;
  const hostname = url.hostname.toLowerCase();
  const segments = url.pathname.split("/").filter(Boolean);
  if (THREADS_HOSTS.has(hostname)) {
    let id;
    let username;
    let kind = "post";
    if (segments.length === 3 && segments[0].startsWith("@") && segments[1] === "post") {
      username = segments[0].slice(1);
      id = segments[2];
      if (!USERNAME_PATTERN.test(username)) return null;
    } else if (segments.length === 2 && (segments[0] === "t" || segments[0] === "share")) {
      kind = segments[0];
      id = segments[1];
    }
    if (!id || !ID_PATTERN.test(id)) return null;
    const path = username ? `/@${username}/post/${id}` : `/${kind}/${id}`;
    return {
      platform: "threads",
      canonicalUrl: `https://www.threads.com${path}`,
      id,
      kind,
      username
    };
  }
  if (INSTAGRAM_HOSTS.has(hostname)) {
    let kind;
    let id;
    if (segments.length === 2 && ["p", "reel", "reels", "tv"].includes(segments[0])) {
      kind = segments[0] === "reels" ? "reel" : segments[0];
      id = segments[1];
    } else if (segments.length === 3 && segments[0] === "share" && segments[1] === "p") {
      kind = "share";
      id = segments[2];
    }
    if (!kind || !id || !ID_PATTERN.test(id)) return null;
    const path = kind === "share" ? `/share/p/${id}` : `/${kind}/${id}`;
    return {
      platform: "instagram",
      canonicalUrl: `https://www.instagram.com${path}`,
      id,
      kind
    };
  }
  return null;
}
function trimUrlPunctuation(candidate) {
  return candidate.replace(/[.,;:!?]+$/g, "").replace(/\)+$/g, (closing) => {
    const openingCount = (candidate.match(/\(/g) ?? []).length;
    const closingCount = (candidate.match(/\)/g) ?? []).length;
    return closing.slice(0, Math.max(0, closingCount - openingCount));
  });
}
function extractSocialUrlMatches(text) {
  const candidates = text.match(/https?:\/\/[^\s<>"'`)\]}]+/gi) ?? [];
  const matches = [];
  for (const candidate of candidates) {
    const raw = trimUrlPunctuation(candidate);
    const parsed = parseSupportedSocialUrl(raw);
    if (parsed) {
      matches.push({
        raw,
        canonicalUrl: parsed.canonicalUrl,
        platform: parsed.platform
      });
    }
  }
  return matches;
}
function extractAllSocialUrls(text) {
  return [
    ...new Set(
      extractSocialUrlMatches(text).map((match) => match.canonicalUrl)
    )
  ];
}
function hostnameMatchesSuffix(hostname, suffix) {
  return hostname === suffix || hostname.endsWith(`.${suffix}`);
}
function validateMediaUrl(value) {
  const url = safeUrl(value);
  if (!url) return null;
  const hostname = url.hostname.toLowerCase();
  const isPlatformHost = THREADS_HOSTS.has(hostname) || INSTAGRAM_HOSTS.has(hostname);
  const isCdnHost = MEDIA_HOST_SUFFIXES.some(
    (suffix) => hostnameMatchesSuffix(hostname, suffix)
  );
  return isPlatformHost || isCdnHost ? url : null;
}
function escapeHtml(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}
function escapeMarkdownText(value) {
  return value.replace(/\\/g, "\\\\").replace(/([`*_{}[\]<>#+.!|~-])/g, "\\$1").replace(/\r?\n/g, " ");
}
function escapeMarkdownUrl(value) {
  return value.replace(/\\/g, "%5C").replace(/\(/g, "%28").replace(/\)/g, "%29");
}
function yamlString(value) {
  const normalized = value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  return JSON.stringify(normalized);
}
function sanitizeFileName(value, fallback = "saved-post") {
  const sanitized = value.normalize("NFC").replace(/[\\/:*?"<>|#^[\]]/g, "-").replace(/[\u0000-\u001F\u007F]/g, "").replace(/\s+/g, " ").replace(/[. ]+$/g, "").trim().slice(0, 120);
  return sanitized || fallback;
}
function sanitizeTag(value) {
  return value.trim().replace(/^#+/, "").replace(/[\s,#[\]]+/g, "-").replace(/[^A-Za-z0-9_\-/À-ÖØ-öø-ÿğüşöçıİĞÜŞÖÇ]/g, "").replace(/-+/g, "-").replace(/^[-/]+|[-/]+$/g, "");
}

// src/downloader.ts
var MAX_MEDIA_ITEMS = 10;
var MAX_MEDIA_BYTES = 20 * 1024 * 1024;
var MAX_TOTAL_MEDIA_BYTES = 100 * 1024 * 1024;
var DOWNLOAD_CONCURRENCY = 3;
var MIME_EXTENSIONS = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "video/mp4": "mp4"
};
function safeVaultPath(value, allowEmpty = false) {
  const raw = value.trim().replace(/\\/g, "/");
  if (!raw && allowEmpty) return "";
  if (!raw || raw.startsWith("/") || raw.split("/").some((segment) => segment === "..")) {
    throw new Error(`Unsafe vault path: ${value}`);
  }
  return (0, import_obsidian.normalizePath)(raw);
}
async function ensureFolderExists(app, folderPath) {
  const normalized = safeVaultPath(folderPath, true);
  if (!normalized || normalized === ".") return;
  const segments = normalized.split("/").filter(Boolean);
  let current = "";
  for (const segment of segments) {
    current = current ? `${current}/${segment}` : segment;
    const existing = app.vault.getAbstractFileByPath(current);
    if (!existing) {
      await app.vault.createFolder(current);
    } else if (!(existing instanceof import_obsidian.TFolder)) {
      throw new Error(`A file blocks the folder path: ${current}`);
    }
  }
}
function getHeader(headers, name) {
  const target = name.toLowerCase();
  const entry = Object.entries(headers).find(
    ([key]) => key.toLowerCase() === target
  );
  return entry?.[1];
}
function remoteMediaMarkdown(item, label) {
  const safeUrl2 = escapeMarkdownUrl(item.url);
  return item.type === "video" ? `[${escapeMarkdownText(label)}](${safeUrl2})` : `![${escapeMarkdownText(label)}](${safeUrl2})`;
}
async function downloadOneMedia(app, folder, job) {
  const validUrl = validateMediaUrl(job.item.url);
  if (!validUrl) {
    return {
      fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
      byteLength: 0
    };
  }
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: validUrl.toString(),
      method: "GET",
      throw: false
    });
    const contentLength = Number(
      getHeader(response.headers, "content-length") ?? "0"
    );
    if (response.status !== 200 || Number.isFinite(contentLength) && contentLength > MAX_MEDIA_BYTES || response.arrayBuffer.byteLength > MAX_MEDIA_BYTES) {
      return {
        fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
        byteLength: 0
      };
    }
    const rawContentType = getHeader(response.headers, "content-type")?.split(";")[0].trim() ?? "";
    const extension = MIME_EXTENSIONS[rawContentType];
    const expectedPrefix = job.item.type === "video" ? "video/" : "image/";
    if (!extension || !rawContentType.startsWith(expectedPrefix)) {
      return {
        fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
        byteLength: 0
      };
    }
    const filePath = (0, import_obsidian.normalizePath)(
      `${folder}/${sanitizeFileName(job.fileStem)}.${extension}`
    );
    const existing = app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      return {
        fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
        existingEmbed: `![[${filePath}]]`,
        byteLength: 0
      };
    }
    if (existing) {
      return {
        fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
        byteLength: 0
      };
    }
    return {
      fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
      filePath,
      binary: response.arrayBuffer,
      byteLength: response.arrayBuffer.byteLength
    };
  } catch {
    return {
      fallbackEmbed: remoteMediaMarkdown(job.item, job.label),
      byteLength: 0
    };
  }
}
function mediaJobs(post, settings) {
  const jobs = [];
  const append = (items, prefix) => {
    for (const item of items) {
      if (item.type === "video" && !settings.downloadVideos) continue;
      const index = jobs.length + 1;
      jobs.push({
        item,
        label: `${item.type === "video" ? "Video" : "Image"} ${index}`,
        fileStem: `${post.platform}_${post.id}_${prefix}_${index}`
      });
      if (jobs.length >= MAX_MEDIA_ITEMS) return;
    }
  };
  append(post.media, "post");
  if (settings.unrollThreadChain && post.replyChain) {
    for (let index = 0; index < post.replyChain.length; index += 1) {
      append(post.replyChain[index].media, `reply_${index + 1}`);
      if (jobs.length >= MAX_MEDIA_ITEMS) break;
    }
  }
  return jobs;
}
async function renderMedia(app, post, settings) {
  if (!settings.includeMedia) return [];
  const jobs = mediaJobs(post, settings);
  if (!settings.downloadMediaLocally) {
    return jobs.map((job) => remoteMediaMarkdown(job.item, job.label));
  }
  const folder = safeVaultPath(
    `${settings.attachmentsFolder}/${post.platform}`
  );
  await ensureFolderExists(app, folder);
  const embeds = [];
  let totalBytes = 0;
  for (let start = 0; start < jobs.length; start += DOWNLOAD_CONCURRENCY) {
    const batch = jobs.slice(start, start + DOWNLOAD_CONCURRENCY);
    if (totalBytes >= MAX_TOTAL_MEDIA_BYTES) {
      embeds.push(
        ...jobs.slice(start).map((job) => remoteMediaMarkdown(job.item, job.label))
      );
      break;
    }
    const results = await Promise.all(
      batch.map((job) => downloadOneMedia(app, folder, job))
    );
    for (let index = 0; index < results.length; index += 1) {
      const result = results[index];
      if (result.existingEmbed) {
        embeds.push(result.existingEmbed);
        continue;
      }
      if (totalBytes + result.byteLength > MAX_TOTAL_MEDIA_BYTES) {
        embeds.push(result.fallbackEmbed);
        continue;
      }
      if (result.binary && result.filePath) {
        try {
          await app.vault.createBinary(result.filePath, result.binary);
          totalBytes += result.byteLength;
          embeds.push(`![[${result.filePath}]]`);
        } catch {
          embeds.push(result.fallbackEmbed);
        }
      } else {
        embeds.push(result.fallbackEmbed);
      }
    }
  }
  return embeds;
}
function quoteMarkdown(value) {
  return value.split(/\r?\n/).map((line) => `> ${escapeMarkdownText(line)}`).join("\n");
}
function formatReplyChain(post) {
  if (!post.replyChain?.length) return "";
  const total = post.replyChain.length + 1;
  const lines = [
    "### Thread chain",
    "",
    `#### 1/${total} @${escapeMarkdownText(post.authorUsername)}`,
    quoteMarkdown(post.content)
  ];
  for (let index = 0; index < post.replyChain.length; index += 1) {
    const reply = post.replyChain[index];
    lines.push(
      "",
      `#### ${index + 2}/${total} @${escapeMarkdownText(reply.authorUsername)}`,
      quoteMarkdown(reply.content)
    );
  }
  return lines.join("\n");
}
function renderVisualPostCard(post, formattedDate, unroll) {
  const replies = unroll ? post.replyChain ?? [] : [];
  const total = replies.length + 1;
  const platformLabel = post.platform === "threads" ? "Threads" : "Instagram";
  const cards = [
    '<div class="threads-thread-container">',
    '  <div class="threads-card">',
    '    <div class="threads-card-header">',
    '      <div class="threads-card-user">',
    `        <span class="threads-card-name">${escapeHtml(post.authorName)}</span>`,
    `        <span class="threads-card-username">@${escapeHtml(post.authorUsername)}${total > 1 ? ` \u2022 1/${total}` : ""}</span>`,
    "      </div>",
    `      <span class="threads-card-badge">${platformLabel}</span>`,
    "    </div>",
    `    <div class="threads-card-body">${escapeHtml(post.content).replace(/\r?\n/g, "<br>")}</div>`,
    '    <div class="threads-card-footer">',
    `      <span>${escapeHtml(formattedDate)}</span>`,
    `      <a class="threads-card-link" href="${escapeHtml(post.url)}">Original post \u2197</a>`,
    "    </div>",
    "  </div>"
  ];
  for (let index = 0; index < replies.length; index += 1) {
    const reply = replies[index];
    cards.push(
      '  <div class="threads-thread-line"></div>',
      '  <div class="threads-card threads-card-reply">',
      '    <div class="threads-card-header">',
      '      <div class="threads-card-user">',
      `        <span class="threads-card-name">${escapeHtml(reply.authorName)}</span>`,
      `        <span class="threads-card-username">@${escapeHtml(reply.authorUsername)} \u2022 ${index + 2}/${total}</span>`,
      "      </div>",
      "    </div>",
      `    <div class="threads-card-body">${escapeHtml(reply.content).replace(/\r?\n/g, "<br>")}</div>`,
      "  </div>"
    );
  }
  cards.push("</div>");
  return cards.join("\n");
}
function replaceTemplate(template, values) {
  return template.replace(
    /\{\{([a-z0-9_]+)\}\}/gi,
    (match, key) => Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match
  );
}
async function generateSocialNoteContent(app, post, settings) {
  const media = await renderMedia(app, post, settings);
  const date = post.timestamp ? new Date(post.timestamp).toISOString().split("T")[0] : (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  const savedAt = (/* @__PURE__ */ new Date()).toISOString();
  const platformLabel = post.platform === "threads" ? "Threads" : "Instagram";
  const tags = [
    ...new Set(
      [
        ...settings.tags.map(sanitizeTag),
        sanitizeTag(`${post.platform}/${post.authorUsername}`)
      ].filter(Boolean)
    )
  ];
  const hasThread = Boolean(
    settings.unrollThreadChain && post.replyChain?.length
  );
  const values = {
    platform: platformLabel,
    platform_yaml: yamlString(post.platform),
    id: post.id,
    id_yaml: yamlString(post.id),
    author_name: escapeMarkdownText(post.authorName),
    author_display_yaml: yamlString(post.authorName),
    author_username: escapeMarkdownText(post.authorUsername),
    author_username_yaml: yamlString(post.authorUsername),
    url: escapeMarkdownUrl(post.url),
    url_yaml: yamlString(post.url),
    date,
    date_yaml: yamlString(date),
    saved_at: savedAt,
    tags: tags.map((tag) => `  - ${yamlString(tag)}`).join("\n"),
    visual_card: settings.useVisualCard ? renderVisualPostCard(post, date, settings.unrollThreadChain) : "",
    content: settings.useVisualCard || hasThread ? "" : quoteMarkdown(post.content),
    media: media.length > 0 ? `### Media

${media.join("\n\n")}` : "",
    reply_chain: settings.unrollThreadChain ? formatReplyChain(post) : ""
  };
  const rawTitle = replaceTemplate(settings.noteTitleTemplate, {
    platform: platformLabel,
    author_username: post.authorUsername,
    author_name: post.authorName,
    id: post.id
  });
  const content = replaceTemplate(settings.noteBodyTemplate, values).replace(/\n{3,}/g, "\n\n").trim().concat("\n");
  return {
    title: sanitizeFileName(rawTitle, `${post.platform}-${post.id}`),
    content
  };
}
function marker(platform, id, side) {
  return `<!-- social-saver:${platform}:${id}:${side} -->`;
}
function wrapManagedContent(post, content) {
  const start = marker(post.platform, post.id, "start");
  const end = marker(post.platform, post.id, "end");
  if (!content.startsWith("---\n")) {
    return `${start}
${content.trim()}
${end}
`;
  }
  const frontmatterEnd = content.indexOf("\n---", 4);
  if (frontmatterEnd < 0) {
    return `${start}
${content.trim()}
${end}
`;
  }
  const splitAt = frontmatterEnd + 4;
  return `${content.slice(0, splitAt)}
${start}
${content.slice(splitAt).trim()}
${end}
`;
}
function stripFrontmatter(content) {
  if (!content.startsWith("---\n")) return content.trim();
  const end = content.indexOf("\n---", 4);
  return end < 0 ? content.trim() : content.slice(end + 4).trim();
}
function replaceManagedBlock(existing, post, block) {
  const start = marker(post.platform, post.id, "start");
  const end = marker(post.platform, post.id, "end");
  const startIndex = existing.indexOf(start);
  const endIndex = existing.indexOf(end, startIndex + start.length);
  if (startIndex < 0 || endIndex < 0) return null;
  return `${existing.slice(0, startIndex)}${block}${existing.slice(endIndex + end.length)}`;
}
function destinationFor(post, settings) {
  if (post.platform === "threads") {
    return {
      mode: settings.threadsSaveMode,
      folder: settings.threadsFolder,
      targetFile: settings.threadsTargetFile
    };
  }
  return {
    mode: settings.instagramSaveMode,
    folder: settings.instagramFolder,
    targetFile: settings.instagramTargetFile
  };
}
async function nextAvailablePath(app, folder, title) {
  const base = (0, import_obsidian.normalizePath)(`${folder}/${title}.md`);
  if (!app.vault.getAbstractFileByPath(base)) return base;
  for (let index = 2; index < 1e4; index += 1) {
    const candidate = (0, import_obsidian.normalizePath)(`${folder}/${title} ${index}.md`);
    if (!app.vault.getAbstractFileByPath(candidate)) return candidate;
  }
  throw new Error("Could not find an available note filename.");
}
async function isManagedPostFile(app, file, post) {
  const existing = await app.vault.read(file);
  return existing.includes(marker(post.platform, post.id, "start")) && existing.includes(marker(post.platform, post.id, "end"));
}
async function findLegacyManagedFile(app, folderPath, post, excludedPaths) {
  const folder = app.vault.getAbstractFileByPath(folderPath);
  if (!(folder instanceof import_obsidian.TFolder)) return null;
  for (const child of folder.children) {
    if (child instanceof import_obsidian.TFile && child.extension === "md" && child.basename.includes(post.id) && !excludedPaths.has(child.path) && await isManagedPostFile(app, child, post)) {
      return child;
    }
  }
  return null;
}
async function saveSocialPostToVault(app, post, settings) {
  const destination = destinationFor(post, settings);
  const generated = await generateSocialNoteContent(app, post, settings);
  if (destination.mode === "single-file") {
    const targetPath = safeVaultPath(
      destination.targetFile.toLowerCase().endsWith(".md") ? destination.targetFile : `${destination.targetFile}.md`
    );
    const parent = targetPath.includes("/") ? targetPath.slice(0, targetPath.lastIndexOf("/")) : "";
    await ensureFolderExists(app, parent);
    const heading = `${generated.title} (${post.id})`;
    const managedBlock = `${marker(post.platform, post.id, "start")}
## ${heading}

${stripFrontmatter(generated.content)}
${marker(post.platform, post.id, "end")}`;
    const existingTarget = app.vault.getAbstractFileByPath(targetPath);
    let file;
    if (!existingTarget) {
      const platformLabel = post.platform === "threads" ? "Threads" : "Instagram";
      file = await app.vault.create(
        targetPath,
        `# ${platformLabel} archive

${managedBlock}
`
      );
    } else if (existingTarget instanceof import_obsidian.TFile) {
      file = existingTarget;
      await app.vault.process(existingTarget, (existing) => {
        const replaced = replaceManagedBlock(existing, post, managedBlock);
        return replaced ?? `${existing.trimEnd()}

${managedBlock}
`;
      });
    } else {
      throw new Error(`The target path is not a Markdown file: ${targetPath}`);
    }
    return { file, subpath: `#${heading}` };
  }
  await ensureFolderExists(app, destination.folder);
  const preferredPath = safeVaultPath(
    `${destination.folder}/${generated.title}.md`
  );
  const managed = wrapManagedContent(post, generated.content);
  const preferred = app.vault.getAbstractFileByPath(preferredPath);
  const identityTitle = sanitizeFileName(
    `${generated.title} - ${post.platform}-${post.id}`
  );
  const identityPath = safeVaultPath(
    `${destination.folder}/${identityTitle}.md`
  );
  const identityFile = app.vault.getAbstractFileByPath(identityPath);
  if (preferred instanceof import_obsidian.TFile && await isManagedPostFile(app, preferred, post)) {
    await app.vault.process(preferred, () => managed);
    return { file: preferred };
  }
  if (identityFile instanceof import_obsidian.TFile && await isManagedPostFile(app, identityFile, post)) {
    await app.vault.process(identityFile, () => managed);
    return { file: identityFile };
  }
  const legacyManaged = await findLegacyManagedFile(
    app,
    destination.folder,
    post,
    /* @__PURE__ */ new Set([preferredPath, identityPath])
  );
  if (legacyManaged) {
    await app.vault.process(legacyManaged, () => managed);
    const targetPath = !preferred ? preferredPath : !identityFile ? identityPath : legacyManaged.path;
    if (targetPath !== legacyManaged.path) {
      await app.fileManager.renameFile(legacyManaged, targetPath);
    }
    return { file: legacyManaged };
  }
  if (!preferred) {
    return { file: await app.vault.create(preferredPath, managed) };
  }
  if (!identityFile) {
    return { file: await app.vault.create(identityPath, managed) };
  }
  const path = await nextAvailablePath(
    app,
    destination.folder,
    identityTitle
  );
  return { file: await app.vault.create(path, managed) };
}

// src/types.ts
var DEFAULT_NOTE_BODY_TEMPLATE = `---
platform: {{platform_yaml}}
social_post_id: {{id_yaml}}
author: {{author_display_yaml}}
username: {{author_username_yaml}}
original_url: {{url_yaml}}
date_saved: {{date_yaml}}
tags:
{{tags}}
---

{{visual_card}}

{{content}}

{{media}}

{{reply_chain}}

---
*Saved with Social Saver on {{saved_at}}*
`;
var DEFAULT_SETTINGS = {
  threadsSaveMode: "folder",
  instagramSaveMode: "folder",
  threadsFolder: "Threads",
  instagramFolder: "Instagram",
  threadsTargetFile: "Threads.md",
  instagramTargetFile: "Instagram.md",
  attachmentsFolder: "attachments/social-saver",
  downloadMediaLocally: true,
  downloadVideos: true,
  includeMedia: true,
  clipboardAutoDetect: false,
  unrollThreadChain: true,
  useVisualCard: false,
  noteTitleTemplate: "{{platform}} - {{author_username}} - {{id}}",
  noteBodyTemplate: DEFAULT_NOTE_BODY_TEMPLATE,
  tags: ["social-archive"],
  customUserAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
};

// src/migrations.ts
var LEGACY_NOTE_TITLE_TEMPLATE = "Threads - {{author_username}} - {{id}}";
var LEGACY_NOTE_BODY_TEMPLATE = `---
author: "{{author_name}} (@{{author_username}})"
username: "{{author_username}}"
original_url: "{{url}}"
date_saved: {{date}}
tags:
{{tags}}
---

{{visual_card}}

{{content}}

{{media}}

{{reply_chain}}

---
*Saved with [Threads Saver](https://github.com/Oguzhan-Ozpinar/obsidian-threads-saver) on {{saved_at}}*
`;
function migrateStoredSettings(stored) {
  const settings = { ...DEFAULT_SETTINGS };
  let migrated = false;
  for (const key of Object.keys(DEFAULT_SETTINGS)) {
    const value = stored[key];
    if (value !== void 0) {
      settings[key] = value;
    }
  }
  if (stored.notesFolder && !stored.threadsFolder) {
    settings.threadsFolder = stored.notesFolder;
    migrated = true;
  }
  if (settings.noteTitleTemplate === LEGACY_NOTE_TITLE_TEMPLATE) {
    settings.noteTitleTemplate = DEFAULT_SETTINGS.noteTitleTemplate;
    migrated = true;
  }
  if (settings.noteBodyTemplate === LEGACY_NOTE_BODY_TEMPLATE) {
    settings.noteBodyTemplate = DEFAULT_NOTE_BODY_TEMPLATE;
    migrated = true;
  }
  if (Array.isArray(settings.tags) && settings.tags.length === 1 && settings.tags[0].trim().toLowerCase() === "threads") {
    settings.tags = [...DEFAULT_SETTINGS.tags];
    migrated = true;
  }
  if (settings.attachmentsFolder === "attachments/threads") {
    settings.attachmentsFolder = DEFAULT_SETTINGS.attachmentsFolder;
    migrated = true;
  }
  return { settings, migrated };
}

// src/parser.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_USER_AGENT = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1";
var MAX_HTML_BYTES = 10 * 1024 * 1024;
var MAX_JSON_BYTES = 2 * 1024 * 1024;
var MAX_JSON_SCRIPTS = 40;
var MAX_JSON_NODES = 12e3;
var MAX_JSON_DEPTH = 35;
var MAX_MEDIA_ITEMS2 = 10;
function isObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}
function asObject(value) {
  return isObject(value) ? value : null;
}
function asArray(value) {
  return Array.isArray(value) ? value : [];
}
function asString(value) {
  return typeof value === "string" ? value : "";
}
function asNumber(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : void 0;
}
function getPath(root, ...keys) {
  let current = root;
  for (const key of keys) {
    const object = asObject(current);
    if (!object) return void 0;
    current = object[key];
  }
  return current;
}
function normalizeSessionCookie(value) {
  if (!value) return void 0;
  const trimmed = value.trim();
  if (!trimmed || /[\r\n]/.test(trimmed)) return void 0;
  const match = trimmed.match(/(?:^|;\s*)sessionid=([^;\s]+)/i);
  const token = match?.[1] ?? trimmed;
  if (!/^[A-Za-z0-9%._:-]+$/.test(token)) return void 0;
  return `sessionid=${token}`;
}
function mediaKey(url) {
  try {
    const parsed = new URL(url);
    return `${parsed.hostname.toLowerCase()}${parsed.pathname}`;
  } catch {
    return url;
  }
}
function isLikelyPostImage(url) {
  const lower = url.toLowerCase();
  return !lower.includes("static.cdninstagram.com") && !lower.includes("rsrc.php") && !lower.includes("profile_pic") && !lower.includes("s150x150");
}
function createMediaCollector() {
  const items = [];
  const seen = /* @__PURE__ */ new Set();
  return {
    items,
    add(url, type) {
      if (items.length >= MAX_MEDIA_ITEMS2 || !url) return;
      if (type === "image" && !isLikelyPostImage(url)) return;
      const valid = validateMediaUrl(url);
      if (!valid) return;
      const key = `${type}:${mediaKey(valid.toString())}`;
      if (seen.has(key)) return;
      seen.add(key);
      items.push({ url: valid.toString(), type });
    }
  };
}
function bestCandidateUrl(value) {
  const candidates = asArray(value).map((item) => asObject(item)).filter((item) => item !== null).sort((a, b) => {
    const aWidth = asNumber(a.width) ?? 0;
    const bWidth = asNumber(b.width) ?? 0;
    return bWidth - aWidth;
  });
  return asString(candidates[0]?.url);
}
function collectMediaFromObject(object, add) {
  const carousel = asArray(object.carousel_media);
  if (carousel.length > 0) {
    for (const rawItem of carousel) {
      const item = asObject(rawItem);
      if (!item) continue;
      const video2 = bestCandidateUrl(item.video_versions);
      if (video2) {
        add(video2, "video");
      } else {
        const image = bestCandidateUrl(
          getPath(item, "image_versions2", "candidates")
        );
        if (image) add(image, "image");
      }
    }
    return;
  }
  const video = bestCandidateUrl(object.video_versions);
  if (video) {
    add(video, "video");
  } else {
    const image = bestCandidateUrl(
      getPath(object, "image_versions2", "candidates")
    );
    if (image) add(image, "image");
  }
}
function walkJson(root, visitor) {
  const stack = [
    { value: root, depth: 0 }
  ];
  const ignoredKeys = /* @__PURE__ */ new Set([
    "profile_pic_url",
    "profile_pic_url_hd",
    "suggested_users",
    "user_recommendations",
    "recs_feed",
    "related_posts"
  ]);
  let visited = 0;
  while (stack.length > 0 && visited < MAX_JSON_NODES) {
    const current = stack.pop();
    if (!current || current.depth > MAX_JSON_DEPTH) continue;
    visited += 1;
    if (Array.isArray(current.value)) {
      for (let index = current.value.length - 1; index >= 0; index -= 1) {
        stack.push({
          value: current.value[index],
          depth: current.depth + 1
        });
      }
      continue;
    }
    const object = asObject(current.value);
    if (!object) continue;
    visitor(object);
    for (const [key, value] of Object.entries(object)) {
      if (!ignoredKeys.has(key) && typeof value === "object" && value) {
        stack.push({ value, depth: current.depth + 1 });
      }
    }
  }
}
function scorePostObject(object, id) {
  const objectId = asString(object.code) || asString(object.shortcode) || asString(object.pk) || asString(object.id);
  const matchesId = objectId === id || objectId.startsWith(`${id}_`);
  if (!matchesId) return 0;
  let score = 100;
  let contentSignals = 0;
  if (asString(getPath(object, "caption", "text"))) score += 20;
  if (asString(getPath(object, "caption", "text"))) contentSignals += 1;
  if (asString(getPath(object, "user", "username")) || asString(getPath(object, "owner", "username")) || asString(object.username)) {
    score += 10;
    contentSignals += 1;
  }
  if (asArray(object.carousel_media).length > 0) {
    score += 10;
    contentSignals += 1;
  }
  if (asArray(getPath(object, "image_versions2", "candidates")).length > 0) {
    score += 5;
    contentSignals += 1;
  }
  if (asArray(object.video_versions).length > 0) {
    score += 5;
    contentSignals += 1;
  }
  return contentSignals > 0 ? score : 1;
}
function extractTimestamp(object) {
  const seconds = asNumber(object.taken_at) ?? asNumber(object.device_timestamp) ?? asNumber(object.created_at);
  if (!seconds) return void 0;
  const milliseconds = seconds > 1e14 ? seconds / 1e3 : seconds > 1e10 ? seconds : seconds * 1e3;
  const date = new Date(milliseconds);
  return Number.isNaN(date.getTime()) ? void 0 : date.toISOString();
}
function getMeta(doc, property) {
  const escaped = property.replace(/"/g, '\\"');
  const element = doc.querySelector(
    `meta[property="${escaped}"], meta[name="${escaped}"]`
  );
  return element?.getAttribute("content")?.trim() ?? "";
}
function cleanDescription(value, platform) {
  let content = value.trim();
  if (platform === "instagram") {
    const quoted = content.match(
      /(?:likes?|comments?).*?\s-\s[^:]+:\s*[“"]([\s\S]*?)[”"]\s*$/i
    );
    if (quoted?.[1]) content = quoted[1].trim();
  }
  return content;
}
function extractInstagramUsernameFromMetaUrl(value, expectedId) {
  try {
    const url = new URL(value);
    const hostname = url.hostname.toLowerCase();
    if (url.protocol !== "https:" || !["instagram.com", "www.instagram.com"].includes(hostname)) {
      return "";
    }
    const segments = url.pathname.split("/").filter(Boolean);
    if (segments.length >= 3 && ["p", "reel", "reels", "tv"].includes(segments[1]) && segments[2] === expectedId && /^[A-Za-z0-9._]+$/.test(segments[0])) {
      return segments[0];
    }
  } catch {
  }
  return "";
}
function extractInstagramEmbedVideoUrls(html) {
  const urls = [];
  const seen = /* @__PURE__ */ new Set();
  const addDecodedUrl = (decoded) => {
    if (typeof decoded !== "string") return;
    const valid = validateMediaUrl(decoded);
    if (!valid) return;
    const normalized = valid.toString();
    if (seen.has(normalized)) return;
    seen.add(normalized);
    urls.push(normalized);
  };
  const directPattern = /"video_url":("(?:\\.|[^"\\])*")/g;
  let directMatch;
  while (urls.length < MAX_MEDIA_ITEMS2 && (directMatch = directPattern.exec(html)) !== null) {
    try {
      addDecodedUrl(JSON.parse(directMatch[1]));
    } catch {
    }
  }
  const escapedPattern = /\\"video_url\\":\\"((?:\\\\.|[^"\\])*)\\"/g;
  let escapedMatch;
  while (urls.length < MAX_MEDIA_ITEMS2 && (escapedMatch = escapedPattern.exec(html)) !== null) {
    let decoded = escapedMatch[1];
    for (let pass = 0; pass < 2; pass += 1) {
      try {
        decoded = JSON.parse(
          `"${decoded.replace(/"/g, '\\"')}"`
        );
      } catch {
        decoded = "";
        break;
      }
    }
    addDecodedUrl(decoded);
  }
  return urls;
}
function authorFromMeta(title, description, fallbackUsername) {
  const usernameMatch = title.match(/\(@([A-Za-z0-9._]+)\)/) ?? description.match(/@([A-Za-z0-9._]+)/);
  const username = usernameMatch?.[1] ?? fallbackUsername;
  const instagramName = title.match(/^(.+?)\s+on Instagram(?::|$)/i)?.[1];
  const nameCandidate = instagramName?.trim() || title.split(/[•|]/)[0].replace(/\(@[^)]+\)/, "").replace(/^@/, "").trim();
  return {
    name: nameCandidate || username || "Unknown author",
    username: username || "unknown"
  };
}
function parseReplyChain(jsonRoots, mainAuthor) {
  const replies = [];
  const seen = /* @__PURE__ */ new Set();
  for (const root of jsonRoots) {
    walkJson(root, (object) => {
      const threadItems = asArray(object.thread_items);
      if (threadItems.length < 2) return;
      for (const rawItem of threadItems.slice(1)) {
        const post = asObject(getPath(rawItem, "post")) ?? asObject(rawItem);
        if (!post) continue;
        const username = asString(getPath(post, "user", "username"));
        if (mainAuthor && username && username.toLowerCase() !== mainAuthor.toLowerCase()) {
          continue;
        }
        const content = asString(getPath(post, "caption", "text"));
        const collector = createMediaCollector();
        collectMediaFromObject(post, collector.add);
        const replyId = asString(post.pk) || asString(post.id) || `${username}:${content}:${collector.items[0]?.url ?? ""}`;
        if (seen.has(replyId) || !content && collector.items.length === 0) {
          continue;
        }
        seen.add(replyId);
        replies.push({
          authorUsername: username || mainAuthor || "unknown",
          authorName: asString(getPath(post, "user", "full_name")) || username || mainAuthor || "Unknown author",
          content,
          media: collector.items
        });
      }
    });
  }
  return replies.slice(0, 20);
}
async function parseSocialPost(inputUrl, sessionCookie, userProvidedUserAgent, options = {}) {
  const parsedUrl = parseSupportedSocialUrl(inputUrl);
  if (!parsedUrl) {
    throw new Error("Unsupported or unsafe Threads/Instagram URL.");
  }
  const headers = {
    "User-Agent": userProvidedUserAgent && userProvidedUserAgent.length <= 300 && !/\r|\n/.test(userProvidedUserAgent) ? userProvidedUserAgent.trim() : DEFAULT_USER_AGENT,
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9"
  };
  const fetchVideos = options.fetchVideos ?? true;
  const cookie = normalizeSessionCookie(sessionCookie);
  const requestPage = async (cookieHeader) => {
    const requestHeaders = { ...headers };
    if (cookieHeader) requestHeaders.Cookie = cookieHeader;
    const page = await (0, import_obsidian2.requestUrl)({
      url: parsedUrl.canonicalUrl,
      method: "GET",
      headers: requestHeaders,
      throw: false
    });
    if (page.status !== 200) {
      throw new Error(
        `${parsedUrl.platform === "threads" ? "Threads" : "Instagram"} returned HTTP ${page.status}.`
      );
    }
    if (page.arrayBuffer.byteLength > MAX_HTML_BYTES) {
      throw new Error("The post page exceeded the safe response-size limit.");
    }
    return page;
  };
  let response = await requestPage();
  let doc = new DOMParser().parseFromString(response.text, "text/html");
  let cookieWasSent = false;
  const initialDescription = getMeta(doc, "og:description") || getMeta(doc, "twitter:description");
  const initialLooksLoggedOut = /Join Threads to share ideas|Log in with your Instagram/i.test(
    initialDescription
  ) || !initialDescription;
  if (cookie && initialLooksLoggedOut && !["share", "t"].includes(parsedUrl.kind)) {
    response = await requestPage(cookie);
    doc = new DOMParser().parseFromString(response.text, "text/html");
    cookieWasSent = true;
  }
  const title = parsedUrl.platform === "instagram" ? getMeta(doc, "twitter:title") || getMeta(doc, "og:title") : getMeta(doc, "og:title") || getMeta(doc, "twitter:title");
  const description = getMeta(doc, "og:description") || getMeta(doc, "twitter:description");
  const canonicalMetaUrl = getMeta(doc, "og:url");
  const ogImage = getMeta(doc, "og:image") || getMeta(doc, "twitter:image");
  const ogVideo = getMeta(doc, "og:video:secure_url") || getMeta(doc, "og:video") || getMeta(doc, "twitter:player:stream");
  const jsonRoots = [];
  const scriptTags = Array.from(
    doc.querySelectorAll('script[type="application/json"]')
  ).slice(0, MAX_JSON_SCRIPTS);
  for (const script of scriptTags) {
    const scriptText = script.textContent?.trim();
    if (!scriptText || new TextEncoder().encode(scriptText).byteLength > MAX_JSON_BYTES || !/(?:thread_items|carousel_media|image_versions2|video_versions|shortcode|caption)/.test(
      scriptText
    )) {
      continue;
    }
    try {
      jsonRoots.push(JSON.parse(scriptText));
    } catch {
    }
  }
  const bestMatch = {
    post: null,
    score: 0
  };
  for (const root of jsonRoots) {
    walkJson(root, (object) => {
      const score = scorePostObject(object, parsedUrl.id);
      if (score > bestMatch.score) {
        bestMatch.score = score;
        bestMatch.post = object;
      }
    });
  }
  const metaUsername = parsedUrl.platform === "instagram" ? extractInstagramUsernameFromMetaUrl(
    canonicalMetaUrl,
    parsedUrl.id
  ) : "";
  const fallbackAuthor = authorFromMeta(
    title,
    description,
    metaUsername || parsedUrl.username || ""
  );
  const postObject = bestMatch.score >= 100 && bestMatch.post ? bestMatch.post : null;
  const authorUsername = (postObject ? asString(getPath(postObject, "user", "username")) || asString(getPath(postObject, "owner", "username")) || asString(postObject.username) : "") || metaUsername || fallbackAuthor.username;
  const authorName = (postObject ? asString(getPath(postObject, "user", "full_name")) || asString(getPath(postObject, "owner", "full_name")) : "") || fallbackAuthor.name;
  const content = (postObject ? asString(getPath(postObject, "caption", "text")) : "") || cleanDescription(description, parsedUrl.platform) || "No text content found in post.";
  const collector = createMediaCollector();
  const addRequestedMedia = (url, type) => {
    if (type === "video" && !fetchVideos) return;
    collector.add(url, type);
  };
  if (postObject) collectMediaFromObject(postObject, addRequestedMedia);
  if (ogVideo && fetchVideos) collector.add(ogVideo, "video");
  if (fetchVideos && parsedUrl.platform === "instagram" && parsedUrl.kind === "reel" && !collector.items.some((item) => item.type === "video")) {
    try {
      const embedResponse = await (0, import_obsidian2.requestUrl)({
        url: `https://www.instagram.com/reel/${parsedUrl.id}/embed/`,
        method: "GET",
        headers,
        throw: false
      });
      if (embedResponse.status === 200 && embedResponse.arrayBuffer.byteLength <= MAX_HTML_BYTES) {
        for (const videoUrl of extractInstagramEmbedVideoUrls(
          embedResponse.text
        )) {
          collector.add(videoUrl, "video");
        }
      }
    } catch {
    }
  }
  if (ogImage && (!fetchVideos || !(parsedUrl.platform === "instagram" && collector.items.some((item) => item.type === "video")))) {
    collector.add(ogImage, "image");
  }
  const genericLandingPage = /Join Threads to share ideas|Log in with your Instagram/i.test(content);
  const missingPostData = !postObject && !description && !ogImage && !ogVideo;
  if (genericLandingPage || missingPostData) {
    throw new Error(
      cookieWasSent ? "Meta returned a login page. The saved sessionid may be expired." : ["share", "t"].includes(parsedUrl.kind) ? "Meta returned a login page for a redirecting short/share link. Retry with the direct post URL." : "Meta returned a login page. Add a sessionid in Social Saver settings, then retry."
    );
  }
  return {
    platform: parsedUrl.platform,
    id: parsedUrl.id,
    url: parsedUrl.canonicalUrl,
    authorName,
    authorUsername,
    content,
    media: collector.items,
    replyChain: parsedUrl.platform === "threads" ? parseReplyChain(jsonRoots, authorUsername) : void 0,
    timestamp: (postObject ? extractTimestamp(postObject) : void 0) ?? (/* @__PURE__ */ new Date()).toISOString()
  };
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var ThreadsSaverSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Account access").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Meta session ID").setDesc(
      "Optional. Used only for validated Threads and Instagram page requests. Stored in Obsidian's secret storage, not the plugin data file. Treat it like a password."
    ).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("sessionid value").setValue(this.plugin.getSessionCookie()).onChange((value) => {
        this.plugin.setSessionCookie(value);
      });
    }).addExtraButton((button) => {
      button.setIcon("eye").setTooltip("Show or hide session ID").onClick(() => {
        const input = button.extraSettingsEl.parentElement?.querySelector(
          'input[type="password"], input[type="text"]'
        );
        if (!input) return;
        input.type = input.type === "password" ? "text" : "password";
        button.setIcon(input.type === "password" ? "eye" : "eye-off");
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Threads destination").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Save mode").setDesc("Create one note per post, or maintain one managed archive file.").addDropdown(
      (dropdown) => dropdown.addOption("folder", "One note per post").addOption("single-file", "Single archive file").setValue(this.plugin.settings.threadsSaveMode).onChange(async (value) => {
        this.plugin.settings.threadsSaveMode = value === "single-file" ? "single-file" : "folder";
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.threadsSaveMode === "folder") {
      new import_obsidian3.Setting(containerEl).setName("Threads folder").setDesc("Vault folder for Threads notes.").addText(
        (text) => text.setPlaceholder("Social/Threads").setValue(this.plugin.settings.threadsFolder).onChange(async (value) => {
          this.plugin.settings.threadsFolder = value.trim() || "Social/Threads";
          await this.plugin.saveSettings();
        })
      );
    } else {
      new import_obsidian3.Setting(containerEl).setName("Threads archive file").setDesc("Markdown file used as the managed Threads archive.").addText(
        (text) => text.setPlaceholder("Social/Threads.md").setValue(this.plugin.settings.threadsTargetFile).onChange(async (value) => {
          this.plugin.settings.threadsTargetFile = value.trim() || "Social/Threads.md";
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Instagram destination").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Save mode").setDesc("Create one note per post, or maintain one managed archive file.").addDropdown(
      (dropdown) => dropdown.addOption("folder", "One note per post").addOption("single-file", "Single archive file").setValue(this.plugin.settings.instagramSaveMode).onChange(async (value) => {
        this.plugin.settings.instagramSaveMode = value === "single-file" ? "single-file" : "folder";
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.instagramSaveMode === "folder") {
      new import_obsidian3.Setting(containerEl).setName("Instagram folder").setDesc("Vault folder for Instagram posts and Reels.").addText(
        (text) => text.setPlaceholder("Social/Instagram").setValue(this.plugin.settings.instagramFolder).onChange(async (value) => {
          this.plugin.settings.instagramFolder = value.trim() || "Social/Instagram";
          await this.plugin.saveSettings();
        })
      );
    } else {
      new import_obsidian3.Setting(containerEl).setName("Instagram archive file").setDesc("Markdown file used as the managed Instagram archive.").addText(
        (text) => text.setPlaceholder("Social/Instagram.md").setValue(this.plugin.settings.instagramTargetFile).onChange(async (value) => {
          this.plugin.settings.instagramTargetFile = value.trim() || "Social/Instagram.md";
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Content and media").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Unroll Threads chains").setDesc("Include sequential replies written by the original author.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.unrollThreadChain).onChange(async (value) => {
        this.plugin.settings.unrollThreadChain = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Include media").setDesc("Include supported post images and videos in saved notes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeMedia).onChange(async (value) => {
        this.plugin.settings.includeMedia = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Download media locally").setDesc("Copy supported media to the vault using size and MIME checks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.downloadMediaLocally).onChange(async (value) => {
        this.plugin.settings.downloadMediaLocally = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Download videos").setDesc("Allow MP4 downloads for Instagram Reels and video posts.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.downloadVideos).onChange(async (value) => {
        this.plugin.settings.downloadVideos = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Attachments folder").setDesc("Platform subfolders are created below this vault folder.").addText(
      (text) => text.setPlaceholder("attachments/social-saver").setValue(this.plugin.settings.attachmentsFolder).onChange(async (value) => {
        this.plugin.settings.attachmentsFolder = value.trim() || "attachments/social-saver";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Visual post card").setDesc("Render escaped post text inside the bundled card style.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useVisualCard).onChange(async (value) => {
        this.plugin.settings.useVisualCard = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Clipboard detection").setDesc(
      "Check the clipboard when Obsidian regains focus and offer to save a supported link."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.clipboardAutoDetect).onChange(async (value) => {
        this.plugin.settings.clipboardAutoDetect = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Templates").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Note title template").setDesc(
      "Variables: {{platform}}, {{author_username}}, {{author_name}}, {{id}}"
    ).addText(
      (text) => text.setPlaceholder("{{platform}} - {{author_username}} - {{id}}").setValue(this.plugin.settings.noteTitleTemplate).onChange(async (value) => {
        this.plugin.settings.noteTitleTemplate = value.trim() || "{{platform}} - {{author_username}} - {{id}}";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Note body template").setDesc(
      "Supports escaped display variables and dedicated *_yaml variables from the default template."
    ).addTextArea((text) => {
      text.inputEl.rows = 12;
      text.inputEl.cols = 55;
      text.setValue(
        this.plugin.settings.noteBodyTemplate || DEFAULT_NOTE_BODY_TEMPLATE
      ).onChange(async (value) => {
        this.plugin.settings.noteBodyTemplate = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Tags").setDesc("Comma-separated default tags.").addText(
      (text) => text.setPlaceholder("social-archive").setValue(this.plugin.settings.tags.join(", ")).onChange(async (value) => {
        this.plugin.settings.tags = value.split(",").map((tag) => tag.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Custom user agent").setDesc("Optional request user agent. Leave empty to use the built-in value.").addText(
      (text) => text.setPlaceholder("Mozilla/5.0 \u2026").setValue(this.plugin.settings.customUserAgent).onChange(async (value) => {
        this.plugin.settings.customUserAgent = value.trim();
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var SESSION_SECRET_ID = "social-saver-sessionid";
function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function errorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}
function inlinePostMarkdown(platform, authorUsername, content, url) {
  const label = platform === "threads" ? "Threads" : "Instagram";
  const quoted = content.split(/\r?\n/).map((line) => `> ${escapeMarkdownText(line)}`).join("\n");
  return `> **@${escapeMarkdownText(authorUsername)}** \xB7 ${label}
${quoted}
> [Original post](${escapeMarkdownUrl(url)})
`;
}
var SocialSaverPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.focusListener = null;
    this.lastProcessedClipboardUrl = "";
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("archive", "Save social post from clipboard", () => {
      void this.handleSaveFromClipboard();
    });
    this.addCommand({
      id: "social-save-from-clipboard",
      name: "Save Threads or Instagram post from clipboard",
      callback: () => this.handleSaveFromClipboard()
    });
    this.addCommand({
      id: "social-insert-at-cursor",
      name: "Insert Threads or Instagram post at cursor",
      editorCallback: (editor) => this.handleInsertAtCursor(editor)
    });
    this.addCommand({
      id: "social-convert-links-in-active-note",
      name: "Process all Threads and Instagram links in active note",
      callback: () => this.handleConvertActiveNoteLinks()
    });
    this.addCommand({
      id: "threads-save-from-clipboard",
      name: "Save social post from clipboard (legacy command)",
      callback: () => this.handleSaveFromClipboard()
    });
    this.addCommand({
      id: "threads-insert-at-cursor",
      name: "Insert social post at cursor (legacy command)",
      editorCallback: (editor) => this.handleInsertAtCursor(editor)
    });
    this.addCommand({
      id: "threads-convert-links-in-active-note",
      name: "Process social links in active note (legacy command)",
      callback: () => this.handleConvertActiveNoteLinks()
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const selection = editor.getSelection();
        const lineNumber = editor.getCursor().line;
        const source = selection || editor.getLine(lineNumber);
        const match = extractSocialUrlMatches(source)[0];
        if (!match) return;
        menu.addItem((item) => {
          item.setTitle("Convert social post link").setIcon("archive").onClick(
            () => this.processAndReplaceLinkInEditor(
              editor,
              match.raw,
              match.canonicalUrl,
              Boolean(selection),
              lineNumber
            )
          );
        });
      })
    );
    const protocolHandler = async (params) => {
      const parsed = params.url ? parseSupportedSocialUrl(params.url) : null;
      if (!parsed) {
        new import_obsidian4.Notice("Deep link contains an unsupported or unsafe URL.");
        return;
      }
      await this.processAndSaveUrl(parsed.canonicalUrl);
    };
    this.registerObsidianProtocolHandler("social-saver", protocolHandler);
    this.registerObsidianProtocolHandler("threads-saver", protocolHandler);
    this.focusListener = () => {
      if (!this.settings.clipboardAutoDetect) return;
      void this.checkClipboardOnFocus();
    };
    window.addEventListener("focus", this.focusListener);
    this.addSettingTab(new ThreadsSaverSettingTab(this.app, this));
  }
  onunload() {
    if (this.focusListener) {
      window.removeEventListener("focus", this.focusListener);
      this.focusListener = null;
    }
  }
  async loadSettings() {
    const stored = await this.loadData() ?? {};
    const migration = migrateStoredSettings(stored);
    this.settings = migration.settings;
    if (stored.sessionCookie && !this.getSessionCookie()) {
      this.setSessionCookie(stored.sessionCookie);
      migration.migrated = true;
    }
    if (stored.sessionCookie || migration.migrated) {
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getSessionCookie() {
    return this.app.secretStorage.getSecret(SESSION_SECRET_ID) ?? "";
  }
  setSessionCookie(value) {
    this.app.secretStorage.setSecret(SESSION_SECRET_ID, value.trim());
  }
  async checkClipboardOnFocus() {
    try {
      const text = await navigator.clipboard.readText();
      const url = extractAllSocialUrls(text)[0];
      if (url && url !== this.lastProcessedClipboardUrl) {
        this.showClipboardNotice(url);
      }
    } catch {
    }
  }
  async handleSaveFromClipboard() {
    try {
      const text = await navigator.clipboard.readText();
      const url = extractAllSocialUrls(text)[0];
      if (!url) {
        new import_obsidian4.Notice(
          "Clipboard does not contain a supported Threads or Instagram URL."
        );
        return;
      }
      await this.processAndSaveUrl(url);
    } catch {
      new import_obsidian4.Notice("Could not read the clipboard. Check Obsidian permissions.");
    }
  }
  async handleConvertActiveNoteLinks() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian4.Notice("No active note is open.");
      return;
    }
    const initialContent = await this.app.vault.read(activeFile);
    const matches = extractSocialUrlMatches(initialContent);
    const urls = [...new Set(matches.map((match) => match.canonicalUrl))];
    if (urls.length === 0) {
      new import_obsidian4.Notice("No supported Threads or Instagram URLs found.");
      return;
    }
    const progress = new import_obsidian4.Notice(`Processing social links: 0/${urls.length}`, 0);
    const saved = /* @__PURE__ */ new Map();
    const failed = [];
    try {
      for (let index = 0; index < urls.length; index += 1) {
        progress.setMessage(
          `Processing social links: ${index + 1}/${urls.length}`
        );
        const result = await this.processAndSaveUrl(urls[index], {
          openFile: false,
          showNotices: false
        });
        if (result) saved.set(urls[index], result);
        else failed.push(urls[index]);
      }
      if (saved.size > 0) {
        await this.app.vault.process(activeFile, (latest) => {
          let updated = latest;
          for (const match of extractSocialUrlMatches(latest)) {
            const result = saved.get(match.canonicalUrl);
            if (!result) continue;
            const noteLink = this.app.fileManager.generateMarkdownLink(
              result.file,
              activeFile.path,
              result.subpath
            );
            const markdownLink = new RegExp(
              `\\[([^\\]\\n]+)\\]\\(${escapeRegExp(match.raw)}\\)`,
              "g"
            );
            updated = updated.replace(
              markdownLink,
              (_full, alias) => this.app.fileManager.generateMarkdownLink(
                result.file,
                activeFile.path,
                result.subpath,
                alias
              )
            );
            updated = updated.split(`<${match.raw}>`).join(noteLink);
            updated = updated.split(match.raw).join(noteLink);
          }
          return updated;
        });
      }
    } finally {
      progress.hide();
    }
    new import_obsidian4.Notice(
      failed.length === 0 ? `Processed ${saved.size} social link(s).` : `Processed ${saved.size}; ${failed.length} failed and remained unchanged.`,
      8e3
    );
  }
  async handleInsertAtCursor(editor) {
    try {
      const text = await navigator.clipboard.readText();
      const url = extractAllSocialUrls(text)[0];
      if (!url) {
        new import_obsidian4.Notice(
          "Clipboard does not contain a supported Threads or Instagram URL."
        );
        return;
      }
      const post = await parseSocialPost(
        url,
        this.getSessionCookie(),
        this.settings.customUserAgent,
        { fetchVideos: false }
      );
      editor.replaceSelection(
        inlinePostMarkdown(
          post.platform,
          post.authorUsername,
          post.content,
          post.url
        )
      );
      new import_obsidian4.Notice("Social post inserted.");
    } catch (error) {
      new import_obsidian4.Notice(`Could not insert post: ${errorMessage(error)}`);
    }
  }
  async processAndReplaceLinkInEditor(editor, rawUrl, canonicalUrl, hasSelection, lineNumber) {
    try {
      const post = await parseSocialPost(
        canonicalUrl,
        this.getSessionCookie(),
        this.settings.customUserAgent,
        { fetchVideos: false }
      );
      const markdown = inlinePostMarkdown(
        post.platform,
        post.authorUsername,
        post.content,
        post.url
      );
      if (hasSelection) {
        editor.replaceSelection(markdown);
      } else {
        const line = editor.getLine(lineNumber);
        const start = line.indexOf(rawUrl);
        if (start < 0) throw new Error("The link moved before it was replaced.");
        editor.replaceRange(
          markdown.trimEnd(),
          { line: lineNumber, ch: start },
          { line: lineNumber, ch: start + rawUrl.length }
        );
      }
      new import_obsidian4.Notice("Social post link converted.");
    } catch (error) {
      new import_obsidian4.Notice(`Could not convert link: ${errorMessage(error)}`);
    }
  }
  async processAndSaveUrl(url, options = {}) {
    const { openFile = true, showNotices = true } = options;
    const parsed = parseSupportedSocialUrl(url);
    if (!parsed) {
      if (showNotices) new import_obsidian4.Notice("Unsupported or unsafe social URL.");
      return null;
    }
    if (showNotices) {
      new import_obsidian4.Notice(
        `Fetching ${parsed.platform === "threads" ? "Threads" : "Instagram"} post\u2026`
      );
    }
    try {
      const post = await parseSocialPost(
        parsed.canonicalUrl,
        this.getSessionCookie(),
        this.settings.customUserAgent,
        {
          fetchVideos: this.settings.includeMedia && this.settings.downloadVideos
        }
      );
      const result = await saveSocialPostToVault(
        this.app,
        post,
        this.settings
      );
      this.lastProcessedClipboardUrl = parsed.canonicalUrl;
      if (openFile) {
        await this.app.workspace.getLeaf(false).openFile(result.file);
      }
      if (showNotices) {
        new import_obsidian4.Notice(
          `Saved ${post.platform === "threads" ? "Threads" : "Instagram"} post.`
        );
      }
      return result;
    } catch (error) {
      console.error("Social Saver could not process the URL:", error);
      if (showNotices) {
        new import_obsidian4.Notice(`Could not save post: ${errorMessage(error)}`, 8e3);
      }
      return null;
    }
  }
  showClipboardNotice(url) {
    const parsed = parseSupportedSocialUrl(url);
    if (!parsed) return;
    const platform = parsed.platform === "threads" ? "Threads" : "Instagram";
    const notice = new import_obsidian4.Notice("", 8e3);
    const container = notice.noticeEl.createDiv({
      cls: "threads-notice-container"
    });
    container.createDiv({ cls: "threads-notice-title" }).setText(`${platform} link detected in clipboard`);
    const actions = container.createDiv({ cls: "threads-notice-actions" });
    const save = actions.createEl("button", {
      text: "Save to vault",
      cls: "threads-btn-primary"
    });
    const ignore = actions.createEl("button", {
      text: "Ignore",
      cls: "threads-btn-secondary"
    });
    save.addEventListener("click", () => {
      notice.hide();
      void this.processAndSaveUrl(parsed.canonicalUrl);
    });
    ignore.addEventListener("click", () => {
      this.lastProcessedClipboardUrl = parsed.canonicalUrl;
      notice.hide();
    });
  }
};
