/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ThreadsSaverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_NOTE_BODY_TEMPLATE = `---
author: "{{author_name}} (@{{author_username}})"
username: "{{author_username}}"
original_url: "{{url}}"
date_saved: {{date}}
tags:
{{tags}}
---

{{visual_card}}

{{content}}

{{media}}

{{reply_chain}}

---
*Saved with [Threads Saver](https://github.com/Oguzhan-Ozpinar/obsidian-threads-saver) on {{saved_at}}*
`;
var DEFAULT_SETTINGS = {
  notesFolder: "Threads",
  attachmentsFolder: "attachments/threads",
  downloadMediaLocally: true,
  includeMedia: true,
  clipboardAutoDetect: true,
  autoEnrichShareSheetLinks: true,
  unrollThreadChain: true,
  useVisualCard: false,
  noteTitleTemplate: "Threads - {{author_username}} - {{id}}",
  noteBodyTemplate: DEFAULT_NOTE_BODY_TEMPLATE,
  tags: ["threads"],
  sessionCookie: "",
  customUserAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var ThreadsSaverSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Threads Saver Settings" });
    new import_obsidian.Setting(containerEl).setName("Session Cookie (sessionid)").setDesc("Threads.net requires a logged-in session cookie to fetch full post content and images. Open threads.net in browser -> Application/Storage -> Cookies -> copy 'sessionid' value.").addText(
      (text) => text.setPlaceholder("e.g. 6428412345%3A...").setValue(this.plugin.settings.sessionCookie).onChange(async (value) => {
        this.plugin.settings.sessionCookie = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Visual Threads Card").setDesc("Render a styled HTML/CSS card in native Threads UI layout at the top of the note (default: OFF).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useVisualCard).onChange(async (value) => {
        this.plugin.settings.useVisualCard = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Unroll Thread Chain").setDesc("Fetch and combine sequential reply posts written by the same author into a single unrolled note.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.unrollThreadChain).onChange(async (value) => {
        this.plugin.settings.unrollThreadChain = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include Media").setDesc("Include post images and media attachments in saved notes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeMedia).onChange(async (value) => {
        this.plugin.settings.includeMedia = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Download Media Locally").setDesc("Download post images into your vault so image links never break when Instagram CDN links expire.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.downloadMediaLocally).onChange(async (value) => {
        this.plugin.settings.downloadMediaLocally = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Clipboard Auto-Detect").setDesc("Show a quick Toast notification to save Threads link when switching back to Obsidian with a Threads URL in clipboard.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.clipboardAutoDetect).onChange(async (value) => {
        this.plugin.settings.clipboardAutoDetect = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-Enrich Share Sheet Links").setDesc("Automatically convert raw Threads URLs shared via mobile Share Sheet into rich Markdown notes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoEnrichShareSheetLinks).onChange(async (value) => {
        this.plugin.settings.autoEnrichShareSheetLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Notes Folder").setDesc("Vault folder where saved Threads posts will be created as Markdown notes.").addText(
      (text) => text.setPlaceholder("Threads").setValue(this.plugin.settings.notesFolder).onChange(async (value) => {
        this.plugin.settings.notesFolder = value.trim() || "Threads";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Attachments Folder").setDesc("Vault folder where post images/media will be downloaded.").addText(
      (text) => text.setPlaceholder("attachments/threads").setValue(this.plugin.settings.attachmentsFolder).onChange(async (value) => {
        this.plugin.settings.attachmentsFolder = value.trim() || "attachments/threads";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Note Title Template").setDesc("Template for note titles. Variables: {{author_username}}, {{author_name}}, {{id}}").addText(
      (text) => text.setPlaceholder("Threads - {{author_username}} - {{id}}").setValue(this.plugin.settings.noteTitleTemplate).onChange(async (value) => {
        this.plugin.settings.noteTitleTemplate = value.trim() || "Threads - {{author_username}} - {{id}}";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Custom Note Body Template").setDesc("Customize the Markdown note layout. Variables: {{visual_card}}, {{author_name}}, {{author_username}}, {{url}}, {{date}}, {{saved_at}}, {{content}}, {{media}}, {{reply_chain}}, {{tags}}").addTextArea((text) => {
      text.inputEl.rows = 8;
      text.inputEl.cols = 50;
      text.setValue(this.plugin.settings.noteBodyTemplate || DEFAULT_NOTE_BODY_TEMPLATE).onChange(async (value) => {
        this.plugin.settings.noteBodyTemplate = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Tags").setDesc("Comma-separated list of default tags to add to saved notes.").addText(
      (text) => text.setPlaceholder("threads, social").setValue(this.plugin.settings.tags.join(", ")).onChange(async (value) => {
        this.plugin.settings.tags = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/parser.ts
var import_obsidian2 = require("obsidian");
function extractThreadsPostId(url) {
  try {
    const cleanUrl = url.trim();
    const postMatch = cleanUrl.match(/threads\.(net|com)\/@([a-zA-Z0-9_.-]+)\/post\/([a-zA-Z0-9_.-]+)/i);
    if (postMatch) {
      return { username: postMatch[2], postId: postMatch[3] };
    }
    const shortMatch = cleanUrl.match(/threads\.(net|com)\/t\/([a-zA-Z0-9_.-]+)/i);
    if (shortMatch) {
      return { postId: shortMatch[2] };
    }
    const shareMatch = cleanUrl.match(/threads\.(net|com)\/share\/([a-zA-Z0-9_.-]+)/i);
    if (shareMatch) {
      return { shareId: shareMatch[2] };
    }
    return null;
  } catch (err) {
    console.error("Error extracting Threads post ID:", err);
    return null;
  }
}
function isThreadsUrl(url) {
  return /https?:\/\/(www\.)?threads\.(net|com)\/(@[a-zA-Z0-9_.-]+\/post\/[a-zA-Z0-9_.-]+|t\/[a-zA-Z0-9_.-]+|share\/[a-zA-Z0-9_.-]+)/i.test(url.trim());
}
function getImageKey(url) {
  try {
    const u = new URL(url);
    return u.pathname.toLowerCase();
  } catch {
    return url.split("?")[0].toLowerCase();
  }
}
function isMainPostImage(url) {
  if (!url)
    return false;
  if (url.includes("static.cdninstagram.com") || url.includes("rsrc.php"))
    return false;
  if (url.includes("s150x150") || url.includes("s320x320") || url.includes("profile_pic"))
    return false;
  return true;
}
async function parseThreadsPost(url, sessionCookie, userProvidedUserAgent) {
  const extracted = extractThreadsPostId(url);
  if (!extracted) {
    throw new Error("Invalid Threads URL format.");
  }
  const targetUrl = url.trim();
  const fallbackId = extracted.postId || extracted.shareId || Date.now().toString();
  const headers = {
    "User-Agent": userProvidedUserAgent || "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin"
  };
  if (sessionCookie && sessionCookie.trim()) {
    const cleanCookie = sessionCookie.trim();
    headers["Cookie"] = cleanCookie.includes("sessionid=") ? cleanCookie : `sessionid=${cleanCookie}`;
  }
  const response = await (0, import_obsidian2.requestUrl)({
    url: targetUrl,
    method: "GET",
    headers
  });
  if (response.status !== 200) {
    throw new Error(`Failed to fetch Threads post (HTTP ${response.status}).`);
  }
  const html = response.text;
  const domParser = new DOMParser();
  const doc = domParser.parseFromString(html, "text/html");
  const getMeta = (property) => {
    const el = doc.querySelector(`meta[property="${property}"], meta[name="${property}"]`);
    return el ? el.getAttribute("content") || "" : "";
  };
  let ogTitle = getMeta("og:title") || getMeta("twitter:title");
  let ogDescription = getMeta("og:description") || getMeta("twitter:description");
  let ogImage = getMeta("og:image") || getMeta("twitter:image");
  let authorUsername = extracted.username || "";
  let authorName = authorUsername ? `@${authorUsername}` : "Threads User";
  let content = ogDescription;
  const isGenericLandingPage = content.includes("Join Threads to share ideas") || content.includes("Log in with your Instagram") || !content.trim();
  if (isGenericLandingPage && (!sessionCookie || !sessionCookie.trim())) {
    throw new Error(
      "Meta Threads blocked unauthenticated fetch. Please add your sessionid cookie in Threads Saver plugin settings to fetch post content!"
    );
  }
  if (ogTitle) {
    const titleMatch = ogTitle.match(/([^•]+)(?:•|\(@([a-zA-Z0-9_.-]+)\))/i);
    if (titleMatch && titleMatch[1]) {
      authorName = titleMatch[1].trim();
    }
  }
  const mediaUrls = [];
  const seenKeys = /* @__PURE__ */ new Set();
  const addMediaUrl = (imgUrl) => {
    if (!imgUrl || !isMainPostImage(imgUrl))
      return;
    const key = getImageKey(imgUrl);
    if (!seenKeys.has(key)) {
      seenKeys.add(key);
      mediaUrls.push(imgUrl);
    }
  };
  const replyChain = [];
  const scriptTags = Array.from(doc.querySelectorAll('script[type="application/json"]'));
  for (const script of scriptTags) {
    const scriptText = script.textContent;
    if (!scriptText)
      continue;
    try {
      if (scriptText.includes("thread_items") || scriptText.includes("carousel_media")) {
        const jsonData = JSON.parse(scriptText);
        extractCarouselMediaOnly(jsonData, addMediaUrl);
        extractThreadUnrollChain(jsonData, authorUsername, replyChain);
      }
    } catch {
    }
  }
  if (mediaUrls.length === 0 && ogImage) {
    addMediaUrl(ogImage);
  }
  if (content && content.startsWith(authorName)) {
    content = content.substring(authorName.length).trim();
  }
  return {
    id: fallbackId,
    url: targetUrl,
    authorName: authorName.replace(/^@/, ""),
    authorUsername: authorUsername || "user",
    content: content || "No text content found in post.",
    mediaUrls,
    replyChain: replyChain.length > 0 ? replyChain : void 0,
    timestamp: (/* @__PURE__ */ new Date()).toISOString()
  };
}
function extractCarouselMediaOnly(obj, addMediaFn) {
  if (!obj || typeof obj !== "object")
    return;
  const ignoredKeys = /* @__PURE__ */ new Set([
    "suggested_users",
    "user_recommendations",
    "recs_feed",
    "profile_pic",
    "user",
    "author",
    "related_posts",
    "header"
  ]);
  if (obj.carousel_media && Array.isArray(obj.carousel_media)) {
    for (const item of obj.carousel_media) {
      if (item.image_versions2 && item.image_versions2.candidates && item.image_versions2.candidates.length > 0) {
        const bestImage = item.image_versions2.candidates[0].url;
        if (bestImage) {
          addMediaFn(bestImage);
        }
      }
    }
    return;
  }
  if (obj.image_versions2 && obj.image_versions2.candidates) {
    const candidates = obj.image_versions2.candidates;
    if (Array.isArray(candidates) && candidates.length > 0) {
      const bestImage = candidates[0].url;
      if (bestImage) {
        addMediaFn(bestImage);
      }
    }
  }
  for (const key of Object.keys(obj)) {
    if (ignoredKeys.has(key))
      continue;
    if (typeof obj[key] === "object") {
      extractCarouselMediaOnly(obj[key], addMediaFn);
    }
  }
}
function extractThreadUnrollChain(obj, mainAuthorUsername, replyChain) {
  if (!obj || typeof obj !== "object")
    return;
  if (obj.thread_items && Array.isArray(obj.thread_items) && obj.thread_items.length > 1) {
    for (let i = 1; i < obj.thread_items.length; i++) {
      const item = obj.thread_items[i];
      if (!item || !item.post)
        continue;
      const postUser = item.post.user?.username || "";
      if (mainAuthorUsername && postUser && postUser.toLowerCase() !== mainAuthorUsername.toLowerCase()) {
        continue;
      }
      const replyText = item.post.caption?.text || "";
      const replyMedia = [];
      if (item.post.carousel_media && Array.isArray(item.post.carousel_media)) {
        for (const c of item.post.carousel_media) {
          if (c.image_versions2?.candidates?.length > 0) {
            replyMedia.push(c.image_versions2.candidates[0].url);
          }
        }
      } else if (item.post.image_versions2?.candidates?.length > 0) {
        replyMedia.push(item.post.image_versions2.candidates[0].url);
      }
      if (replyText || replyMedia.length > 0) {
        replyChain.push({
          authorUsername: postUser || mainAuthorUsername,
          authorName: item.post.user?.full_name || postUser || mainAuthorUsername,
          content: replyText,
          mediaUrls: replyMedia.filter(isMainPostImage)
        });
      }
    }
  }
  for (const key of Object.keys(obj)) {
    if (typeof obj[key] === "object" && key !== "suggested_users" && key !== "recs_feed") {
      extractThreadUnrollChain(obj[key], mainAuthorUsername, replyChain);
    }
  }
}

// src/downloader.ts
var import_obsidian3 = require("obsidian");
async function ensureFolderExists(app, folderPath) {
  const normalized = (0, import_obsidian3.normalizePath)(folderPath);
  if (normalized === "" || normalized === ".")
    return;
  const folder = app.vault.getAbstractFileByPath(normalized);
  if (!folder) {
    await app.vault.createFolder(normalized);
  }
}
async function downloadMediaLocally(app, post, attachmentsFolder) {
  const mainMediaEmbeds = [];
  const replyMediaEmbeds = [];
  await ensureFolderExists(app, attachmentsFolder);
  for (let i = 0; i < post.mediaUrls.length; i++) {
    const mediaUrl = post.mediaUrls[i];
    try {
      const extensionMatch = mediaUrl.match(/\.(jpg|jpeg|png|webp)/i);
      const ext = extensionMatch ? extensionMatch[1] : "jpg";
      const fileName = `threads_${post.id}_${i + 1}.${ext}`;
      const filePath = (0, import_obsidian3.normalizePath)(`${attachmentsFolder}/${fileName}`);
      const existingFile = app.vault.getAbstractFileByPath(filePath);
      if (existingFile instanceof import_obsidian3.TFile) {
        mainMediaEmbeds.push(`![[${filePath}]]`);
        continue;
      }
      const response = await (0, import_obsidian3.requestUrl)({ url: mediaUrl, method: "GET" });
      if (response.status === 200 && response.arrayBuffer) {
        await app.vault.createBinary(filePath, response.arrayBuffer);
        mainMediaEmbeds.push(`![[${filePath}]]`);
      } else {
        mainMediaEmbeds.push(`![Media ${i + 1}](${mediaUrl})`);
      }
    } catch {
      mainMediaEmbeds.push(`![Media ${i + 1}](${mediaUrl})`);
    }
  }
  if (post.replyChain && post.replyChain.length > 0) {
    for (let rIdx = 0; rIdx < post.replyChain.length; rIdx++) {
      const reply = post.replyChain[rIdx];
      for (let mIdx = 0; mIdx < reply.mediaUrls.length; mIdx++) {
        const mUrl = reply.mediaUrls[mIdx];
        try {
          const fileName = `threads_${post.id}_reply${rIdx + 1}_${mIdx + 1}.jpg`;
          const filePath = (0, import_obsidian3.normalizePath)(`${attachmentsFolder}/${fileName}`);
          const existingFile = app.vault.getAbstractFileByPath(filePath);
          if (existingFile instanceof import_obsidian3.TFile) {
            replyMediaEmbeds.push(`![[${filePath}]]`);
            continue;
          }
          const resp = await (0, import_obsidian3.requestUrl)({ url: mUrl, method: "GET" });
          if (resp.status === 200 && resp.arrayBuffer) {
            await app.vault.createBinary(filePath, resp.arrayBuffer);
            replyMediaEmbeds.push(`![[${filePath}]]`);
          } else {
            replyMediaEmbeds.push(`![Reply Media ${mIdx + 1}](${mUrl})`);
          }
        } catch {
          replyMediaEmbeds.push(`![Reply Media ${mIdx + 1}](${mUrl})`);
        }
      }
    }
  }
  return { mainMediaEmbeds, replyMediaEmbeds };
}
function formatReplyChainMarkdown(post) {
  const replyChain = post.replyChain;
  if (!replyChain || replyChain.length === 0)
    return "";
  const totalCount = 1 + replyChain.length;
  const lines = ["\n### \u{1F9F5} Thread Chain (Unrolled)"];
  lines.push(`
#### 1/${totalCount} @${post.authorUsername}`);
  if (post.content) {
    lines.push(`> ${post.content.replace(/\n/g, "\n> ")}`);
  }
  for (let i = 0; i < replyChain.length; i++) {
    const item = replyChain[i];
    lines.push(`
#### ${i + 2}/${totalCount} @${item.authorUsername}`);
    if (item.content) {
      lines.push(`> ${item.content.replace(/\n/g, "\n> ")}`);
    }
  }
  return lines.join("\n\n");
}
function renderVisualPostCard(post, formattedDate, unrollChain) {
  const totalCount = unrollChain && post.replyChain ? 1 + post.replyChain.length : 1;
  const counterBadge = totalCount > 1 ? ` \u2022 1/${totalCount}` : "";
  let cardsHtml = `<div class="threads-thread-container">
  <div class="threads-card">
    <div class="threads-card-header">
      <div class="threads-card-user">
        <span class="threads-card-name">${post.authorName}</span>
        <span class="threads-card-username">@${post.authorUsername}${counterBadge}</span>
      </div>
      <span class="threads-card-badge">Threads</span>
    </div>
    <div class="threads-card-body">${post.content}</div>
    <div class="threads-card-footer">
      <span>${formattedDate}</span>
      <a class="threads-card-link" href="${post.url}" target="_blank">Original Post \u2197</a>
    </div>
  </div>`;
  if (unrollChain && post.replyChain && post.replyChain.length > 0) {
    for (let i = 0; i < post.replyChain.length; i++) {
      const reply = post.replyChain[i];
      cardsHtml += `
  <div class="threads-thread-line"></div>
  <div class="threads-card threads-card-reply">
    <div class="threads-card-header">
      <div class="threads-card-user">
        <span class="threads-card-name">${reply.authorName || reply.authorUsername}</span>
        <span class="threads-card-username">@${reply.authorUsername} \u2022 ${i + 2}/${totalCount}</span>
      </div>
    </div>
    <div class="threads-card-body">${reply.content}</div>
  </div>`;
    }
  }
  cardsHtml += `
</div>`;
  return cardsHtml;
}
async function generateThreadsNoteContent(app, post, settings) {
  let allMediaEmbeds = [];
  if (settings.includeMedia) {
    if (settings.downloadMediaLocally) {
      const downloaded = await downloadMediaLocally(app, post, settings.attachmentsFolder);
      allMediaEmbeds = [...downloaded.mainMediaEmbeds, ...downloaded.replyMediaEmbeds];
    } else {
      allMediaEmbeds = post.mediaUrls.map((url, idx) => `![Image ${idx + 1}](${url})`);
      if (post.replyChain) {
        for (const r of post.replyChain) {
          for (const u of r.mediaUrls) {
            allMediaEmbeds.push(`![Reply Image](${u})`);
          }
        }
      }
    }
  }
  const tagsFormatted = settings.tags.map((t) => t.trim().replace(/^#/, "")).concat([`threads/${post.authorUsername}`]).map((t) => `  - ${t}`).join("\n");
  const formattedDate = post.timestamp ? new Date(post.timestamp).toISOString().split("T")[0] : (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  const savedAt = (/* @__PURE__ */ new Date()).toLocaleString();
  const hasReplyChain = settings.unrollThreadChain && post.replyChain && post.replyChain.length > 0;
  const mediaSection = settings.includeMedia && allMediaEmbeds.length > 0 ? "### Media\n" + allMediaEmbeds.join("\n\n") : "";
  const replyChainSection = settings.unrollThreadChain ? formatReplyChainMarkdown(post) : "";
  const visualCardHtml = settings.useVisualCard ? renderVisualPostCard(post, formattedDate, settings.unrollThreadChain) : "";
  const contentBlock = settings.useVisualCard || hasReplyChain ? "" : `> ${post.content.replace(/\n/g, "\n> ")}`;
  const bodyTemplate = settings.noteBodyTemplate || "";
  const noteContent = bodyTemplate.replace(/\{\{visual_card\}\}/g, visualCardHtml).replace(/\{\{author_name\}\}/g, post.authorName).replace(/\{\{author_username\}\}/g, post.authorUsername).replace(/\{\{url\}\}/g, post.url).replace(/\{\{date\}\}/g, formattedDate).replace(/\{\{saved_at\}\}/g, savedAt).replace(/\{\{content\}\}/g, contentBlock).replace(/\{\{media\}\}/g, mediaSection).replace(/\{\{reply_chain\}\}/g, replyChainSection).replace(/\{\{tags\}\}/g, tagsFormatted);
  const cleanedContent = noteContent.replace(/\n\n\n+/g, "\n\n");
  const cleanTitle = settings.noteTitleTemplate.replace("{{author_username}}", post.authorUsername).replace("{{author_name}}", post.authorName).replace("{{id}}", post.id).replace(/[^a-zA-Z0-9 _-]/g, "");
  return {
    title: cleanTitle,
    content: cleanedContent
  };
}
async function saveThreadsPostToVault(app, post, settings) {
  await ensureFolderExists(app, settings.notesFolder);
  const { title, content } = await generateThreadsNoteContent(app, post, settings);
  const filePath = (0, import_obsidian3.normalizePath)(`${settings.notesFolder}/${title}.md`);
  const existingFile = app.vault.getAbstractFileByPath(filePath);
  if (existingFile instanceof import_obsidian3.TFile) {
    await app.vault.modify(existingFile, content);
    new import_obsidian3.Notice(`Updated Threads note: ${title}`);
    return existingFile;
  } else {
    const newFile = await app.vault.create(filePath, content);
    new import_obsidian3.Notice(`Saved Threads note: ${title}`);
    return newFile;
  }
}

// src/main.ts
function extractAllThreadsUrls(text) {
  const matches = text.match(/https?:\/\/(www\.)?threads\.(net|com)\/(@[a-zA-Z0-9_.-]+\/post\/[a-zA-Z0-9_.-]+|t\/[a-zA-Z0-9_.-]+|share\/[a-zA-Z0-9_.-]+)/gi);
  return matches ? Array.from(new Set(matches.map((m) => m.trim()))) : [];
}
var ThreadsSaverPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.focusListener = null;
    this.lastProcessedClipboardUrl = "";
    this.processingFiles = /* @__PURE__ */ new Set();
  }
  async onload() {
    console.log("Loading Threads Saver Plugin");
    await this.loadSettings();
    this.addRibbonIcon("at-sign", "Save Threads Post from Clipboard", () => {
      this.handleSaveFromClipboard();
    });
    this.addCommand({
      id: "threads-save-from-clipboard",
      name: "Save Threads Post from Clipboard",
      callback: () => this.handleSaveFromClipboard()
    });
    this.addCommand({
      id: "threads-insert-at-cursor",
      name: "Insert Threads Post at Cursor",
      editorCallback: (editor) => this.handleInsertAtCursor(editor)
    });
    this.addCommand({
      id: "threads-convert-links-in-active-note",
      name: "Convert Threads Links in Active Note",
      callback: () => this.handleConvertActiveNoteLinks()
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const selectedText = editor.getSelection().trim();
        const cursorLine = editor.getLine(editor.getCursor().line).trim();
        const targetText = selectedText || cursorLine;
        const urls = extractAllThreadsUrls(targetText);
        if (urls.length > 0) {
          menu.addItem((item) => {
            item.setTitle("Convert Threads Link").setIcon("at-sign").onClick(async () => {
              await this.processAndReplaceLinkInEditor(editor, urls[0]);
            });
          });
        }
      })
    );
    this.registerObsidianProtocolHandler("threads-saver", async (params) => {
      if (params.url) {
        new import_obsidian4.Notice("Processing Threads URL from share...");
        await this.processAndSaveUrl(params.url);
      }
    });
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (!this.settings.autoEnrichShareSheetLinks)
          return;
        if (file instanceof import_obsidian4.TFile && file.extension === "md") {
          setTimeout(async () => {
            await this.checkAndEnrichShareSheetFile(file);
          }, 400);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (!this.settings.autoEnrichShareSheetLinks)
          return;
        if (file instanceof import_obsidian4.TFile && file.extension === "md") {
          if (this.processingFiles.has(file.path))
            return;
          setTimeout(async () => {
            await this.checkAndEnrichShareSheetFile(file);
          }, 600);
        }
      })
    );
    this.focusListener = async () => {
      if (!this.settings.clipboardAutoDetect)
        return;
      try {
        if (navigator.clipboard && navigator.clipboard.readText) {
          const text = await navigator.clipboard.readText();
          const trimmed = text.trim();
          if (isThreadsUrl(trimmed) && trimmed !== this.lastProcessedClipboardUrl) {
            this.showClipboardNotice(trimmed);
          }
        }
      } catch {
      }
    };
    window.addEventListener("focus", this.focusListener);
    this.addSettingTab(new ThreadsSaverSettingTab(this.app, this));
  }
  onunload() {
    console.log("Unloading Threads Saver Plugin");
    if (this.focusListener) {
      window.removeEventListener("focus", this.focusListener);
      this.focusListener = null;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Reads clipboard and saves Threads post.
   */
  async handleSaveFromClipboard() {
    try {
      const text = await navigator.clipboard.readText();
      const trimmed = text.trim();
      const urls = extractAllThreadsUrls(trimmed);
      if (urls.length === 0) {
        new import_obsidian4.Notice("Clipboard does not contain a valid Threads URL.");
        return;
      }
      await this.processAndSaveUrl(urls[0]);
    } catch {
      new import_obsidian4.Notice("Could not read clipboard. Please check app permissions.");
    }
  }
  /**
   * Converts all raw Threads URLs in active note.
   */
  async handleConvertActiveNoteLinks() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian4.Notice("No active note open.");
      return;
    }
    const content = await this.app.vault.read(activeFile);
    const urls = extractAllThreadsUrls(content);
    if (urls.length === 0) {
      new import_obsidian4.Notice("No raw Threads URLs found in active note.");
      return;
    }
    new import_obsidian4.Notice(`Found ${urls.length} Threads URL(s). Processing...`);
    for (const url of urls) {
      await this.processAndSaveUrl(url);
    }
  }
  /**
   * Fetches Threads post and inserts Markdown at active editor cursor.
   */
  async handleInsertAtCursor(editor) {
    try {
      const text = await navigator.clipboard.readText();
      const trimmed = text.trim();
      const urls = extractAllThreadsUrls(trimmed);
      if (urls.length === 0) {
        new import_obsidian4.Notice("Clipboard does not contain a valid Threads URL.");
        return;
      }
      new import_obsidian4.Notice("Fetching Threads post content...");
      const post = await parseThreadsPost(urls[0], this.settings.sessionCookie, this.settings.customUserAgent);
      const markdown = `> **@${post.authorUsername}**: ${post.content}
> [Original Post](${post.url})
`;
      editor.replaceSelection(markdown);
      new import_obsidian4.Notice("Inserted Threads post into note!");
    } catch (err) {
      new import_obsidian4.Notice(`Error inserting Threads post: ${err.message}`);
    }
  }
  /**
   * Processes a Threads URL and replaces it in current editor.
   */
  async processAndReplaceLinkInEditor(editor, url) {
    new import_obsidian4.Notice("Fetching Threads post details...");
    try {
      const post = await parseThreadsPost(url, this.settings.sessionCookie, this.settings.customUserAgent);
      const { content } = await generateThreadsNoteContent(this.app, post, this.settings);
      editor.replaceSelection(content);
      new import_obsidian4.Notice("Converted Threads link into enriched content!");
    } catch (err) {
      new import_obsidian4.Notice(`Failed to convert link: ${err.message}`);
    }
  }
  /**
   * Fetches Threads post and saves to vault as a NEW note.
   */
  async processAndSaveUrl(url) {
    new import_obsidian4.Notice("Fetching Threads post details...");
    try {
      const post = await parseThreadsPost(url, this.settings.sessionCookie, this.settings.customUserAgent);
      const savedFile = await saveThreadsPostToVault(this.app, post, this.settings);
      this.lastProcessedClipboardUrl = url;
      const leaf = this.app.workspace.getUnpackagedLeaf ? this.app.workspace.getUnpackagedLeaf() : this.app.workspace.getLeaf(false);
      await leaf.openFile(savedFile);
      return savedFile;
    } catch (err) {
      console.error("Error processing Threads URL:", err);
      new import_obsidian4.Notice(`Failed to save Threads post: ${err.message || err}`);
      return null;
    }
  }
  /**
   * Checks if a file contains a raw Threads URL line (e.g. from Mobile Share Sheet),
   * saves it as a NEW separate note in Threads folder, and cleans up temp share file.
   */
  async checkAndEnrichShareSheetFile(file) {
    if (this.processingFiles.has(file.path))
      return;
    try {
      const content = await this.app.vault.read(file);
      const urls = extractAllThreadsUrls(content);
      if (urls.length === 0)
        return;
      const lines = content.split("\n");
      const isTempShareFile = lines.length <= 3 && urls.length >= 1;
      if (isTempShareFile || content.trim() === urls[0]) {
        this.processingFiles.add(file.path);
        new import_obsidian4.Notice("Enriching shared Threads post link into new note...");
        const post = await parseThreadsPost(urls[0], this.settings.sessionCookie, this.settings.customUserAgent);
        const newFile = await saveThreadsPostToVault(this.app, post, this.settings);
        const leaf = this.app.workspace.getUnpackagedLeaf ? this.app.workspace.getUnpackagedLeaf() : this.app.workspace.getLeaf(false);
        await leaf.openFile(newFile);
        if (file.path !== newFile.path && !file.path.startsWith(this.settings.notesFolder)) {
          await this.app.vault.delete(file);
        }
        this.processingFiles.delete(file.path);
      }
    } catch {
      this.processingFiles.delete(file.path);
    }
  }
  /**
   * Shows an interactive toast notice when a Threads link is detected in clipboard on app focus.
   */
  showClipboardNotice(url) {
    const noticeEl = new import_obsidian4.Notice("", 8e3);
    const container = noticeEl.noticeEl.createDiv({ cls: "threads-notice-container" });
    const titleEl = container.createDiv({ cls: "threads-notice-title" });
    titleEl.setText("\u{1F4CC} Threads link detected in clipboard!");
    const actionsEl = container.createDiv({ cls: "threads-notice-actions" });
    const saveBtn = actionsEl.createEl("button", {
      text: "Save to Vault",
      cls: "threads-btn-primary"
    });
    const ignoreBtn = actionsEl.createEl("button", {
      text: "Ignore",
      cls: "threads-btn-secondary"
    });
    saveBtn.addEventListener("click", async () => {
      noticeEl.hide();
      await this.processAndSaveUrl(url);
    });
    ignoreBtn.addEventListener("click", () => {
      this.lastProcessedClipboardUrl = url;
      noticeEl.hide();
    });
  }
};
